name: 'gh-semver-match'
description: 'Match semantic versions from repositories'
author: 'cpunion'

inputs:
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  repos:
    description: 'List of repositories to match versions from'
    required: true

outputs:
  matched_versions:
    description: 'JSON string of matched versions'

runs:
  using: 'node20'
  main: 'dist/index.js'
